### ISSUE TITLE
Build failure on Windows platform

### ISSUE THREAD

**Issue by cschol** [ODDSound/MTS-ESP-VCVRack#1]
For library integration, we are cross-compiling on Linux for Windows platform. 

The build fails with the following error:

```
x86_64-w64-mingw32-g++  -std=c++11 -Wsuggest-override   -fPIC -I/home/build/rack-plugin-toolchain/Rack-SDK/include -I/home/build/rack-plugin-toolchain/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/plugin.cpp.o src/plugin.cpp
src/libMTSClient.cpp:16:10: fatal error: shlobj_core.h: No such file or directory
 #include <shlobj_core.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

The Rack toolchain is available here if you want to create a Docker container with the build environment for troubleshooting this or catch future issues early: https://github.com/VCVRack/rack-plugin-toolchain

**Comment by olicash** [comment]
Ah right, nice one.  Have committed a fix, thanks!

source code: https://github.com/ODDSound/MTS-ESP-VCVRack
version: v1.0.0
branch: main
commit hash: c28aa5d

**Comment by cschol** [comment]
Works. Thank you for the fix!
